### ISSUE TITLE
Error reading negative values of latitude and longitude

### ISSUE THREAD

**Issue by MarlonDyo** [mpiannucci/grippy#3]
When you call from LatitudeLongitudeGridTemplate the methods start_latitude, start_longitude, end_latitude, end_longitude on data generated with negative values of either latitude or longitude, the return values are wrong.
I implemented this fix to correct the error:
```
    @property
    def end_longitude(self):
        aux = _uint32.unpack_from(self._data, 59)[0]*(10**-6)
        if self._data[59] >= 128:
            return -aux + 2147.483648
        return aux
```
This is because the GRIB notation has the first bit encode the signal. 
Note that x80 x00 x00 x00 = 2.147.483.648

**Comment by mpiannucci** [comment]
Thank you!!! Any chance you want to send a pull request??

**Comment by MarlonDyo** [comment]
Oh, actually I realized I've made a mistake.
I was adapting your code to run on "GFS 0.25 Degree" grib filter files, 
but notations seems to be slightly different.
Your example code is great. (except from the "from ." imports)

So sorry, your code helped me a lot! Thank you!
